apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: taskpulse
type: Opaque
stringData:
  MYSQL_USER: taskpulse
  MYSQL_PASSWORD: taskpulse_dev
  MYSQL_ROOT_PASSWORD: taskpulse_root_dev
